"use client";

import { useEffect, useState, use } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { PurchaseOrder, POItem } from "@/types/po";
import { authenticatedFetch } from "@/lib/api";
import { AgGridReact } from "ag-grid-react";
import type { ColDef, ValueFormatterParams } from "ag-grid-community";

// AG Grid styles
import "ag-grid-community/styles/ag-grid.css";
import "ag-grid-community/styles/ag-theme-quartz.css";

// Mock data for fallback
async function getMockPO(poNumber: string): Promise<PurchaseOrder | null> {
  try {
    const response = await fetch("/test_PO_response.json");
    const data: PurchaseOrder[] = await response.json();
    const po = data.find((p) => p.PONumber === poNumber);
    if (po) {
      if (!po.PO || po.PO.length === 0) {
        po.PO = ["PO-108248-Uneek.pdf"];
      }
      return po;
    }
    return null;
  } catch (error) {
    console.error("Error loading mock data:", error);
    return null;
  }
}

export default function CompletedItemsPage({ params }: { params: Promise<{ poNumber: string }> }) {
  const { poNumber } = use(params);
  const router = useRouter();
  const [po, setPo] = useState<PurchaseOrder | null>(null);
  const [items, setItems] = useState<POItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [usingMock, setUsingMock] = useState(false);

  useEffect(() => {
    const fetchPO = async () => {
      try {
        const decodedPoNumber = decodeURIComponent(poNumber);
        
        // Try to fetch from API first
        try {
          const res = await authenticatedFetch(`/po/${decodedPoNumber}`);
          if (res.ok) {
            const data: PurchaseOrder = await res.json();
            setPo(data);
            // Show all items regardless of completeness
            const allItems = data.AutoGeneratedContent || [];
            setItems(allItems);
            setLoading(false);
            return;
          } else {
            // If API returns an error, log it but continue to mock data fallback
            const errorText = await res.text();
            console.warn("API fetch failed with status:", res.status, errorText);
          }
        } catch (apiError) {
          console.warn("API fetch failed, trying mock data:", apiError);
        }

        // Fallback to mock data
        const mockPO = await getMockPO(decodedPoNumber);
        if (mockPO) {
          setPo(mockPO);
          // Show all items regardless of completeness
          const allItems = mockPO.AutoGeneratedContent || [];
          setItems(allItems);
          setUsingMock(true);
        } else {
          console.error("PO not found in mock data either");
        }
      } catch (error) {
        console.error("Error fetching PO:", error);
      } finally {
        setLoading(false);
      }
    };

    fetchPO();
  }, [poNumber]);

  const dateFormatter = (params: ValueFormatterParams<POItem, Date | string | null>) => {
    if (!params.value) return "";
    const date = typeof params.value === "string" ? new Date(params.value) : params.value;
    if (isNaN(date.getTime())) return "";
    return date.toLocaleDateString("en-IN", { year: "numeric", month: "2-digit", day: "2-digit" });
  };

  const columnDefs: ColDef<POItem>[] = [
    { 
      headerName: "Vendor Style Code", 
      field: "VendorStyleCode", 
      sortable: true, 
      filter: true,
      width: 160,
      minWidth: 140,
    },
    { 
      headerName: "Item Ref No", 
      field: "ItemRefNo", 
      sortable: true, 
      filter: true,
      width: 140,
      minWidth: 120,
    },
    { 
      headerName: "Item PO No", 
      field: "ItemPoNo", 
      sortable: true, 
      filter: true,
      width: 130,
      minWidth: 110,
    },
    { 
      headerName: "Order Qty", 
      field: "OrderQty", 
      sortable: true,
      width: 110,
      minWidth: 100,
      valueFormatter: (p: ValueFormatterParams<POItem, number>) => {
        return p.value?.toString() ?? "0";
      },
    },
    { 
      headerName: "Metal", 
      field: "Metal", 
      sortable: true, 
      filter: true,
      width: 120,
      minWidth: 100,
    },
    { 
      headerName: "Tone", 
      field: "Tone", 
      sortable: true, 
      filter: true,
      width: 120,
      minWidth: 100,
    },
    { 
      headerName: "Category", 
      field: "Category", 
      sortable: true, 
      filter: true,
      width: 130,
      minWidth: 110,
    },
    { 
      headerName: "Stock Type", 
      field: "StockType", 
      sortable: true, 
      filter: true,
      width: 130,
      minWidth: 110,
      valueFormatter: (p: ValueFormatterParams<POItem, string | null>) => {
        return p.value ?? "";
      },
    },
    { 
      headerName: "Make Type", 
      field: "MakeType", 
      sortable: true, 
      filter: true,
      width: 130,
      minWidth: 110,
      valueFormatter: (p: ValueFormatterParams<POItem, string | null>) => {
        return p.value ?? "";
      },
    },
    { 
      headerName: "Item Size", 
      field: "ItemSize", 
      sortable: true, 
      filter: true,
      width: 120,
      minWidth: 100,
      valueFormatter: (p: ValueFormatterParams<POItem, string | null>) => {
        return p.value ?? "";
      },
    },
    { 
      headerName: "Deadline Date", 
      field: "DeadlineDate", 
      sortable: true,
      width: 140,
      minWidth: 120,
      valueFormatter: dateFormatter,
    },
    { 
      headerName: "Shipping Date", 
      field: "ShippingDate", 
      sortable: true,
      width: 140,
      minWidth: 120,
      valueFormatter: dateFormatter,
    },
    { 
      headerName: "Invoice Number", 
      field: "InvoiceNumber", 
      sortable: true, 
      filter: true,
      width: 150,
      minWidth: 130,
    },
    { 
      headerName: "Customer Production Instruction", 
      field: "CustomerProductionInstruction", 
      sortable: true, 
      filter: true,
      flex: 1,
      minWidth: 200,
      valueFormatter: (p: ValueFormatterParams<POItem, string | null>) => {
        return p.value ?? "";
      },
      tooltipValueGetter: (params) => params.value ?? "",
    },
    { 
      headerName: "Special Remarks", 
      field: "SpecialRemarks", 
      sortable: true, 
      filter: true,
      flex: 1,
      minWidth: 150,
      valueFormatter: (p: ValueFormatterParams<POItem, string | null>) => {
        return p.value ?? "";
      },
      tooltipValueGetter: (params) => params.value ?? "",
    },
    { 
      headerName: "Design Production Instruction", 
      field: "DesignProductionInstruction", 
      sortable: true, 
      filter: true,
      flex: 1,
      minWidth: 200,
      valueFormatter: (p: ValueFormatterParams<POItem, string | null>) => {
        return p.value ?? "";
      },
      tooltipValueGetter: (params) => params.value ?? "",
    },
    { 
      headerName: "Stamp Instruction", 
      field: "StampInstruction", 
      sortable: true, 
      filter: true,
      flex: 1,
      minWidth: 150,
      valueFormatter: (p: ValueFormatterParams<POItem, string | null>) => {
        return p.value ?? "";
      },
      tooltipValueGetter: (params) => params.value ?? "",
    },
  ];

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-screen bg-gradient-to-br from-slate-50 to-slate-100">
        <div className="text-center">
          <svg className="animate-spin h-12 w-12 text-blue-600 mx-auto mb-4" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
            <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
            <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
          </svg>
          <div className="text-lg font-medium text-slate-700">Loading items...</div>
        </div>
      </div>
    );
  }

  if (!po) {
    return (
      <div className="flex items-center justify-center min-h-screen bg-gradient-to-br from-slate-50 to-slate-100">
        <div className="text-center">
          <div className="w-16 h-16 rounded-full bg-red-100 flex items-center justify-center mx-auto mb-4">
            <svg className="w-8 h-8 text-red-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
            </svg>
          </div>
          <div className="text-xl font-semibold text-slate-900 mb-2">PO not found</div>
          <div className="text-slate-600 mb-6">The purchase order you&apos;re looking for doesn&apos;t exist.</div>
          <Link
            href="/"
            className="inline-flex items-center px-4 py-2 rounded-lg bg-blue-600 text-white font-medium hover:bg-blue-700 transition-colors"
          >
            Back to Dashboard
          </Link>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 to-slate-100">
      <div className="flex flex-col gap-6 p-6 max-w-[95vw] mx-auto">
        {/* Header */}
        <header className="bg-white rounded-xl shadow-sm border border-slate-200 p-6 flex items-center justify-between">
          <div>
            <h1 className="text-3xl font-bold bg-gradient-to-r from-blue-600 to-indigo-600 bg-clip-text text-transparent">
              All Items - {decodeURIComponent(poNumber)}
            </h1>
            <p className="text-sm text-slate-600 mt-1 flex items-center gap-2">
              <span className="font-medium">{po.ClientName}</span>
              <span>•</span>
              <span>{items.length} {items.length === 1 ? "item" : "items"}</span>
              {usingMock && (
                <span className="ml-2 text-xs font-medium text-orange-600 bg-orange-50 border border-orange-200 px-2 py-1 rounded-full">
                  Mock Data
                </span>
              )}
            </p>
          </div>
          <div className="flex items-center gap-3">
            <Link
              href={`/review/${encodeURIComponent(poNumber)}`}
              className="px-4 py-2 rounded-lg border border-blue-300 bg-blue-50 hover:bg-blue-100 text-blue-700 font-medium transition-colors flex items-center gap-2"
            >
              <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
              </svg>
              Review PO
            </Link>
            <Link
              href="/"
              className="px-4 py-2 rounded-lg border border-slate-300 bg-white hover:bg-slate-50 text-slate-700 font-medium transition-colors flex items-center gap-2"
            >
              <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 19l-7-7m0 0l7-7m-7 7h18" />
              </svg>
              Dashboard
            </Link>
          </div>
        </header>

        {/* Data Grid */}
        {items.length === 0 ? (
          <div className="bg-white rounded-xl shadow-sm border border-slate-200 p-12 text-center">
            <div className="w-16 h-16 rounded-full bg-slate-200 flex items-center justify-center mx-auto mb-4">
              <svg className="w-8 h-8 text-slate-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
              </svg>
            </div>
            <p className="text-slate-700 font-medium mb-1">No items</p>
            <p className="text-sm text-slate-500">There are no items for this PO yet.</p>
          </div>
        ) : (
          <div className="bg-white rounded-xl shadow-sm border border-slate-200 overflow-hidden">
            <div className="ag-theme-quartz w-full h-[calc(100vh-250px)] min-h-[600px]">
              <AgGridReact<POItem>
                rowData={items}
                columnDefs={columnDefs}
                animateRows
                pagination
                paginationAutoPageSize
                paginationPageSize={20}
                rowHeight={56}
                headerHeight={56}
                suppressHorizontalScroll={false}
                enableCellTextSelection={true}
                ensureDomOrder={true}
                defaultColDef={{
                  resizable: true,
                  sortable: true,
                  filter: false,
                }}
              />
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

