"use client";

import { useEffect, useState, use } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { PurchaseOrder, POItem } from "@/types/po";
import ItemCard from "../components/ItemCard";
import EmailDialog from "../components/EmailDialog";
import { getApiEndpoint } from "@/lib/api";

// Mock data for fallback
async function getMockPO(poNumber: string): Promise<PurchaseOrder | null> {
  try {
    const response = await fetch("/test_PO_response.json");
    const data: PurchaseOrder[] = await response.json();
    const po = data.find((p) => p.PONumber === poNumber);
    if (po) {
      // Ensure PO array has at least one entry
      if (!po.PO || po.PO.length === 0) {
        po.PO = ["PO-108248-Uneek.pdf"];
      }
      return po;
    }
    return null;
  } catch (error) {
    console.error("Error loading mock data:", error);
    return null;
  }
}

export default function ReviewPage({ params }: { params: Promise<{ poNumber: string }> }) {
  const { poNumber } = use(params);
  const router = useRouter();
  const [po, setPo] = useState<PurchaseOrder | null>(null);
  const [items, setItems] = useState<POItem[]>([]);
  const [currentIndex, setCurrentIndex] = useState(0);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [pdfUrl, setPdfUrl] = useState<string>("");
  const [usingMock, setUsingMock] = useState(false);
  const [isAddingNewItem, setIsAddingNewItem] = useState(false);
  const [hasExportedOnce, setHasExportedOnce] = useState(false);
  const [isEmailDialogOpen, setIsEmailDialogOpen] = useState(false);
  const [emailContent, setEmailContent] = useState<string>("");
  const [isDeleting, setIsDeleting] = useState(false);
  const [showDeleteConfirm, setShowDeleteConfirm] = useState(false);

  useEffect(() => {
    const fetchPO = async () => {
      try {
        const decodedPoNumber = decodeURIComponent(poNumber);
        
        // Try to fetch from API first
        try {
          const res = await fetch(getApiEndpoint(`/po/${decodedPoNumber}`));
          if (res.ok) {
            const data: PurchaseOrder = await res.json();
            setPo(data);
            // Initialize items from AutoGeneratedContent
            setItems([...data.AutoGeneratedContent]);
            
            // Set PDF URL - always use backend endpoint to proxy through backend
            if (data.PO && data.PO.length > 0) {
              const s3Url = data.PO.find((p: string) => p.startsWith("http://") || p.startsWith("https://"));
              const pdfPath = s3Url || data.PO.find((p: string) => p.includes("uploads/")) || data.PO[0];
              // Always use backend endpoint to proxy S3 files and local files
              setPdfUrl(getApiEndpoint(`/po/${decodedPoNumber}/pdf?file=${encodeURIComponent(pdfPath)}`));
            }
            setLoading(false);
            return;
          }
        } catch (apiError) {
          console.warn("API fetch failed, trying mock data:", apiError);
        }

        // Fallback to mock data
        const mockPO = await getMockPO(decodedPoNumber);
        if (mockPO) {
          setPo(mockPO);
          setItems([...mockPO.AutoGeneratedContent]);
          setUsingMock(true);
          
          // For mock data, set a placeholder PDF URL or handle gracefully
          if (mockPO.PO && mockPO.PO.length > 0) {
            const s3Url = mockPO.PO.find((p: string) => p.startsWith("http://") || p.startsWith("https://"));
            const pdfPath = s3Url || mockPO.PO.find((p: string) => p.includes("uploads/")) || mockPO.PO[0];
            // Always use backend endpoint to proxy S3 files and local files
            setPdfUrl(getApiEndpoint(`/po/${decodedPoNumber}/pdf?file=${encodeURIComponent(pdfPath)}`));
          }
        } else {
          console.error("PO not found in mock data either");
        }
      } catch (error) {
        console.error("Error fetching PO:", error);
      } finally {
        setLoading(false);
      }
    };

    fetchPO();
  }, [poNumber]);

  const handleToggleIncomplete = (index: number) => {
    const updatedItems = [...items];
    updatedItems[index] = {
      ...updatedItems[index],
      IsIncomplete: !updatedItems[index].IsIncomplete,
    };
    setItems(updatedItems);
  };

  const handleUpdateItem = (index: number, item: POItem) => {
    const updatedItems = [...items];
    updatedItems[index] = item;
    setItems(updatedItems);
  };

  const createBlankItem = (): POItem => {
    return {
      IsIncomplete: true,
      VendorStyleCode: "",
      ItemRefNo: "",
      ItemPoNo: "",
      OrderQty: 0,
      Metal: "",
      Tone: "",
      Category: "",
      StockType: null,
      MakeType: null,
      CustomerProductionInstruction: null,
      SpecialRemarks: null,
      DesignProductionInstruction: null,
      StampInstruction: null,
      ItemSize: null,
      DeadlineDate: null,
      ShippingDate: null,
      InvoiceNumber: "",
    };
  };

  const handleAddItem = () => {
    const blankItem = createBlankItem();
    const updatedItems = [...items];
    // Insert the new item just before the current item (at currentIndex)
    updatedItems.splice(currentIndex, 0, blankItem);
    setItems(updatedItems);
    setIsAddingNewItem(true);
    // The currentIndex stays the same, which now points to the new blank item
  };

  const handleSaveNewItem = () => {
    setIsAddingNewItem(false);
    // Item is already in the items array, just exit add mode
  };

  const handleCancelNewItem = () => {
    const updatedItems = [...items];
    // Remove the item at currentIndex (the temporary new item)
    updatedItems.splice(currentIndex, 1);
    setItems(updatedItems);
    setIsAddingNewItem(false);
    // Adjust currentIndex if we removed the last item
    if (currentIndex >= updatedItems.length && updatedItems.length > 0) {
      setCurrentIndex(updatedItems.length - 1);
    } else if (updatedItems.length === 0) {
      setCurrentIndex(0);
    }
  };

  const handlePrevious = () => {
    if (currentIndex > 0) {
      setCurrentIndex(currentIndex - 1);
    }
  };

  const handleNext = () => {
    if (currentIndex < items.length - 1) {
      setCurrentIndex(currentIndex + 1);
    }
  };

  const handleExportCompletedItems = async () => {
    if (!po || !items.length) return;

    const completedItems = items.filter((item) => !item.IsIncomplete);
    if (completedItems.length === 0) {
      alert("There are no completed items to export yet.");
      return;
    }

    const xlsx = await import("xlsx");

    const exportRows = completedItems.map((item) => {
      const normalizeDate = (value: POItem["DeadlineDate"]) => {
        if (!value) return "";
        const d = typeof value === "string" ? new Date(value) : new Date(value);
        return isNaN(d.getTime()) ? "" : d.toISOString().split("T")[0];
      };

      return {
        VendorStyleCode: item.VendorStyleCode ?? "",
        ItemRefNo: item.ItemRefNo ?? "",
        ItemPoNo: item.ItemPoNo ?? "",
        OrderQty: item.OrderQty ?? 0,
        Metal: item.Metal ?? "",
        Tone: item.Tone ?? "",
        Category: item.Category ?? "",
        StockType: item.StockType ?? "",
        MakeType: item.MakeType ?? "",
        CustomerProductionInstruction: item.CustomerProductionInstruction ?? "",
        SpecialRemarks: item.SpecialRemarks ?? "",
        DesignProductionInstruction: item.DesignProductionInstruction ?? "",
        StampInstruction: item.StampInstruction ?? "",
        ItemSize: item.ItemSize ?? "",
        DeadlineDate: normalizeDate(item.DeadlineDate),
        ShippingDate: normalizeDate(item.ShippingDate),
        InvoiceNumber: item.InvoiceNumber ?? "",
      };
    });

    const worksheet = xlsx.utils.json_to_sheet(exportRows);
    const workbook = xlsx.utils.book_new();
    xlsx.utils.book_append_sheet(workbook, worksheet, "Completed Items");

    const safePONumber = (po.PONumber || decodeURIComponent(poNumber)).replace(/[^\w\-]+/g, "_");
    xlsx.writeFile(workbook, `${safePONumber}_completed_items.xlsx`);

    setHasExportedOnce(true);
  };

  const generateEmailContent = (): string => {
    if (!po || !items.length) return "";

    const incompleteItems = items.filter((item) => item.IsIncomplete);
    if (incompleteItems.length === 0) {
      return "All items are complete. No email needed.";
    }

    // Field labels mapping - only include important fields
    const fieldChecks: Array<{ key: keyof POItem; label: string }> = [
      { key: "VendorStyleCode", label: "Vendor Style Code" },
      { key: "ItemRefNo", label: "Item Ref No" },
      { key: "Metal", label: "Metal" },
      { key: "Tone", label: "Tone" },
      { key: "Category", label: "Category" },
      { key: "OrderQty", label: "Order Quantity" },
      { key: "StockType", label: "Stock Type" },
      { key: "MakeType", label: "Make Type" },
      { key: "ItemSize", label: "Item Size" },
      { key: "DeadlineDate", label: "Deadline Date" },
      { key: "ShippingDate", label: "Shipping Date" },
      { key: "CustomerProductionInstruction", label: "Customer Production Instruction" },
      { key: "SpecialRemarks", label: "Special Remarks" },
      { key: "DesignProductionInstruction", label: "Design Production Instruction" },
      { key: "StampInstruction", label: "Stamp Instruction" },
    ];

    // Helper function to check if a field is missing/empty
    const isFieldMissing = (item: POItem, field: keyof POItem): boolean => {
      const value = item[field];
      if (value === null || value === undefined) return true;
      if (typeof value === "string" && value.trim() === "") return true;
      return false;
    };

    // Build email content - short and precise
    let email = `Subject: Missing Details for PO ${po.PONumber}\n\n`;
    email += `Dear ${po.ClientName},\n\n`;
    email += `Please provide the following missing information for PO ${po.PONumber}:\n\n`;

    incompleteItems.forEach((item, index) => {
      const missingFields: string[] = [];
      
      fieldChecks.forEach(({ key, label }) => {
        if (isFieldMissing(item, key)) {
          missingFields.push(label);
        }
      });

      if (missingFields.length > 0) {
        // Use item identifier or index
        const identifier = item.VendorStyleCode || item.ItemRefNo || item.ItemPoNo || `Item ${index + 1}`;
        email += `${index + 1}. ${identifier}\n`;
        email += `   Missing: ${missingFields.join(", ")}\n\n`;
      }
    });

    email += `Please respond at your earliest convenience.\n\nThank you.`;

    return email;
  };

  const handleGenerateEmail = () => {
    const content = generateEmailContent();
    setEmailContent(content);
    setIsEmailDialogOpen(true);
  };

  const handleDeletePO = async () => {
    if (!po || usingMock) {
      alert("Cannot delete PO in mock mode");
      return;
    }

    setIsDeleting(true);
    try {
      const res = await fetch(getApiEndpoint(`/po/${po.PONumber}`), {
        method: "DELETE",
      });

      if (!res.ok) {
        const errorData = await res.json().catch(() => ({ message: "Delete failed" }));
        throw new Error(errorData.message || errorData.error || "Failed to delete PO");
      }

      // Navigate back to dashboard after successful deletion
      router.push("/");
    } catch (error) {
      console.error("Error deleting PO:", error);
      const errorMessage = error instanceof Error ? error.message : "Failed to delete PO. Please try again.";
      alert(errorMessage);
    } finally {
      setIsDeleting(false);
      setShowDeleteConfirm(false);
    }
  };

  const handleFinishReview = async () => {
    if (!po) return;

    setSaving(true);
    try {
      // Normalize items data - convert dates to strings
      // This matches the API's expected format
      const normalizedItems = items.map((item) => {
        const normalized = {
          IsIncomplete: item.IsIncomplete,
          VendorStyleCode: item.VendorStyleCode,
          ItemRefNo: item.ItemRefNo,
          ItemPoNo: item.ItemPoNo,
          OrderQty: item.OrderQty,
          Metal: item.Metal,
          Tone: item.Tone,
          Category: item.Category,
          StockType: item.StockType ?? null,
          MakeType: item.MakeType ?? null,
          CustomerProductionInstruction: item.CustomerProductionInstruction ?? null,
          SpecialRemarks: item.SpecialRemarks ?? null,
          DesignProductionInstruction: item.DesignProductionInstruction ?? null,
          StampInstruction: item.StampInstruction ?? null,
          ItemSize: item.ItemSize ?? null,
          DeadlineDate: item.DeadlineDate
            ? typeof item.DeadlineDate === "string"
              ? item.DeadlineDate
              : new Date(item.DeadlineDate).toISOString().split("T")[0]
            : null,
          ShippingDate: item.ShippingDate
            ? typeof item.ShippingDate === "string"
              ? item.ShippingDate
              : new Date(item.ShippingDate).toISOString().split("T")[0]
            : null,
          InvoiceNumber: item.InvoiceNumber,
        };

        return normalized;
      });

      // Update the PO with reviewed items - ensure data format matches API expectations
      const updatedPO = {
        ...po,
        PODate: typeof po.PODate === "string" ? po.PODate : new Date(po.PODate).toISOString().split("T")[0],
        Items: normalizedItems,
        AutoGeneratedContent: normalizedItems,
        IncompleteItems: normalizedItems.filter((item) => item.IsIncomplete).length,
        Status: items.some((item) => item.IsIncomplete)
          ? "Reviewed & Incomplete"
          : "Reviewed",
        ClientReminderCount: po.ClientReminderCount ?? null,
      };

      // Only try to save if not using mock data
      if (!usingMock) {
        const res = await fetch(getApiEndpoint(`/po/${po.PONumber}`), {
          method: "PUT",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify(updatedPO),
        });

        if (!res.ok) {
          // Try to get error message from response
          let errorMessage = "Failed to save review";
          try {
            const errorData = await res.json();
            errorMessage = errorData.error || errorData.message || errorMessage;
          } catch {
            errorMessage = `Failed to save review: ${res.status} ${res.statusText}`;
          }
          throw new Error(errorMessage);
        }
      } else {
        console.log("Mock mode: Review data would be saved:", updatedPO);
      }

      // Navigate back to home page
      router.push("/");
    } catch (error) {
      console.error("Error saving review:", error);
      const errorMessage = error instanceof Error ? error.message : "Failed to save review. Please try again.";
      alert(errorMessage);
    } finally {
      setSaving(false);
    }
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <div className="text-lg">Loading...</div>
      </div>
    );
  }

  if (!po) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <div className="text-lg text-red-600">PO not found</div>
      </div>
    );
  }

  const currentItem = items[currentIndex];
  const hasIncomplete = items.length > 0 && items.some((item) => item.IsIncomplete);
  const incompleteCount = items.filter((item) => item.IsIncomplete).length;
  const completedCount = items.length - incompleteCount;

  return (
    <div className="flex flex-col h-screen bg-gray-50">
      {/* Header */}
      <div className="bg-white border-b border-gray-200 px-6 py-4 flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">
            Review PO: {decodeURIComponent(poNumber)}
            {usingMock && (
              <span className="ml-2 text-sm font-normal text-orange-600 bg-orange-50 px-2 py-1 rounded">
                (Mock Data)
              </span>
            )}
          </h1>
          <p className="text-sm text-gray-600 mt-1">
            {po.ClientName} • {items.length} items • {incompleteCount} incomplete
          </p>
        </div>
        <div className="flex items-center gap-3">
          <button
            onClick={handleGenerateEmail}
            disabled={!hasIncomplete || items.length === 0}
            className={`px-4 py-2 rounded-md border font-medium transition-colors ${
              !hasIncomplete || items.length === 0
                ? "border-gray-300 bg-gray-100 text-gray-400 cursor-not-allowed"
                : "border-blue-300 bg-white hover:bg-blue-50 text-blue-700"
            }`}
          >
            Generate Email Content
          </button>
          {!usingMock && (
            <button
              onClick={() => setShowDeleteConfirm(true)}
              disabled={isDeleting}
              className="px-4 py-2 rounded-md border border-red-300 bg-white hover:bg-red-50 text-red-700 font-medium transition-colors disabled:bg-gray-100 disabled:text-gray-400 disabled:cursor-not-allowed"
            >
              {isDeleting ? "Deleting..." : "Delete PO"}
            </button>
          )}
          <Link
            href="/"
            className="px-4 py-2 rounded-md border border-gray-300 bg-white hover:bg-gray-100 text-gray-700 font-medium transition-colors"
          >
            Back to Dashboard
          </Link>
        </div>
      </div>

      {/* Main Content */}
      <div className="flex-1 flex overflow-hidden">
        {/* Left Side - PDF Viewer */}
        <div className="w-1/2 border-r border-gray-200 bg-gray-100 flex flex-col min-w-0">
          <div className="bg-white border-b border-gray-200 px-4 py-3 shrink-0">
            <h2 className="text-lg font-semibold text-gray-900">PO Document</h2>
            {po?.PO && po.PO.length > 0 && (
              <p className="text-sm text-gray-600 mt-1">
                {po.PO[0].split('/').pop() || po.PO[0]}
              </p>
            )}
          </div>
          <div className="flex-1 overflow-hidden p-4">
            {pdfUrl ? (
              <iframe
                src={pdfUrl}
                className="w-full h-full border border-gray-300 rounded-lg bg-white min-h-0"
                title="PO PDF"
                style={{ minHeight: 0 }}
              />
            ) : (
              <div className="flex items-center justify-center h-full text-gray-500">
                <div className="text-center">
                  <p className="mb-2">No PDF available</p>
                  <p className="text-sm text-gray-400">PDF viewer will appear here when available</p>
                </div>
              </div>
            )}
          </div>
        </div>

        {/* Right Side - Item Review */}
        <div className="w-1/2 flex flex-col bg-white">
          <div className="bg-gray-50 border-b border-gray-200 px-4 py-3 flex items-center justify-between">
            <h2 className="text-lg font-semibold text-gray-900">Item Review</h2>
            <div className="flex flex-col items-end text-sm text-gray-600">
              <span>
                Progress: {currentIndex + 1} / {items.length}
              </span>
              <span className="text-xs text-gray-500">
                Completed: {completedCount} {completedCount === 1 ? "item" : "items"}
              </span>
            </div>
          </div>

          <div className="flex-1 overflow-auto p-6">
            {currentItem ? (
              <ItemCard
                item={currentItem}
                index={currentIndex}
                totalItems={items.length}
                onToggleIncomplete={handleToggleIncomplete}
                onUpdateItem={handleUpdateItem}
                isNewItem={isAddingNewItem}
                onSaveNewItem={handleSaveNewItem}
                onCancelNewItem={handleCancelNewItem}
              />
            ) : (
              <div className="flex items-center justify-center h-full text-gray-500">
                <div className="text-center">
                  <p className="mb-2">No items to review</p>
                  <p className="text-sm text-gray-400">Items will appear here when available</p>
                </div>
              </div>
            )}
          </div>

          {/* Navigation Footer */}
          <div className="border-t border-gray-200 bg-gray-50 px-6 py-4">
            <div className="flex items-center justify-between">
              <button
                onClick={handlePrevious}
                disabled={currentIndex === 0 || isAddingNewItem}
                className={`px-4 py-2 rounded-md font-medium transition-colors ${
                  currentIndex === 0 || isAddingNewItem
                    ? "bg-gray-200 text-gray-400 cursor-not-allowed"
                    : "bg-white border border-gray-300 text-gray-700 hover:bg-gray-50"
                }`}
              >
                ← Previous
              </button>

              <div className="flex items-center gap-3">
                {!isAddingNewItem && (
                  <button
                    onClick={handleAddItem}
                    className="px-4 py-2 rounded-md bg-green-600 text-white font-medium hover:bg-green-700 transition-colors"
                  >
                    + Add Item
                  </button>
                )}
                {hasIncomplete && !isAddingNewItem && (
                  <span className="text-sm text-red-600 font-medium">
                    ⚠️ {incompleteCount} incomplete item(s)
                  </span>
                )}
                {!isAddingNewItem && completedCount > 0 && (
                  <button
                    type="button"
                    onClick={handleExportCompletedItems}
                    className="px-4 py-2 rounded-md border border-blue-300 bg-white text-blue-700 text-sm font-medium hover:bg-blue-50 transition-colors"
                  >
                    {hasExportedOnce ? "Export Completed Items Again" : "Export Completed Items (Excel)"}
                  </button>
                )}
                {!isAddingNewItem && (
                  <button
                    onClick={handleFinishReview}
                    disabled={saving}
                    className="px-6 py-2 rounded-md bg-blue-600 text-white font-medium hover:bg-blue-700 disabled:bg-blue-400 disabled:cursor-not-allowed transition-colors"
                  >
                    {saving ? "Saving..." : "Finish Review"}
                  </button>
                )}
              </div>

              <button
                onClick={handleNext}
                disabled={currentIndex === items.length - 1 || isAddingNewItem}
                className={`px-4 py-2 rounded-md font-medium transition-colors ${
                  currentIndex === items.length - 1 || isAddingNewItem
                    ? "bg-gray-200 text-gray-400 cursor-not-allowed"
                    : "bg-white border border-gray-300 text-gray-700 hover:bg-gray-50"
                }`}
              >
                Next →
              </button>
            </div>
          </div>
        </div>
      </div>
      
      <EmailDialog
        isOpen={isEmailDialogOpen}
        onClose={() => setIsEmailDialogOpen(false)}
        emailContent={emailContent}
      />

      {/* Delete Confirmation Dialog */}
      {showDeleteConfirm && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
          <div className="bg-white rounded-lg p-6 max-w-md w-full mx-4">
            <h2 className="text-xl font-bold text-gray-900 mb-4">Delete Purchase Order</h2>
            <p className="text-gray-700 mb-6">
              Are you sure you want to delete PO <strong>{po?.PONumber}</strong>? This action cannot be undone and will delete:
              <ul className="list-disc list-inside mt-2 text-sm text-gray-600">
                <li>The PO from the database</li>
                <li>All associated items</li>
                <li>All files from S3</li>
                <li>All file metadata</li>
              </ul>
            </p>
            <div className="flex justify-end gap-3">
              <button
                onClick={() => setShowDeleteConfirm(false)}
                disabled={isDeleting}
                className="px-4 py-2 rounded-md border border-gray-300 bg-white hover:bg-gray-100 text-gray-700 font-medium transition-colors disabled:opacity-50"
              >
                Cancel
              </button>
              <button
                onClick={handleDeletePO}
                disabled={isDeleting}
                className="px-4 py-2 rounded-md bg-red-600 text-white font-medium hover:bg-red-700 transition-colors disabled:bg-red-400 disabled:cursor-not-allowed"
              >
                {isDeleting ? "Deleting..." : "Delete"}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}


