"use client";

import { useEffect, useState, use } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { PurchaseOrder, POItem } from "@/types/po";
import ItemCard from "../components/ItemCard";

// Mock data for fallback
async function getMockPO(poNumber: string): Promise<PurchaseOrder | null> {
  try {
    const response = await fetch("/test_PO_response.json");
    const data: PurchaseOrder[] = await response.json();
    const po = data.find((p) => p.PONumber === poNumber);
    if (po) {
      // Ensure PO array has at least one entry
      if (!po.PO || po.PO.length === 0) {
        po.PO = ["PO-108248-Uneek.pdf"];
      }
      return po;
    }
    return null;
  } catch (error) {
    console.error("Error loading mock data:", error);
    return null;
  }
}

export default function ReviewPage({ params }: { params: Promise<{ poNumber: string }> }) {
  const { poNumber } = use(params);
  const router = useRouter();
  const [po, setPo] = useState<PurchaseOrder | null>(null);
  const [items, setItems] = useState<POItem[]>([]);
  const [currentIndex, setCurrentIndex] = useState(0);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [pdfUrl, setPdfUrl] = useState<string>("");
  const [usingMock, setUsingMock] = useState(false);
  const [isAddingNewItem, setIsAddingNewItem] = useState(false);

  useEffect(() => {
    const fetchPO = async () => {
      try {
        const decodedPoNumber = decodeURIComponent(poNumber);
        
        // Try to fetch from API first
        try {
          const res = await fetch(`http://localhost:4000/api/pos/${decodedPoNumber}`);
          if (res.ok) {
            const data: PurchaseOrder = await res.json();
            setPo(data);
            // Initialize items from AutoGeneratedContent
            setItems([...data.AutoGeneratedContent]);
            
            // Set PDF URL - prefer uploads path, otherwise use first available
            if (data.PO && data.PO.length > 0) {
              // Find uploads path first, or use the first one
              const pdfPath = data.PO.find((p: string) => p.includes("uploads/")) || data.PO[0];
              // Check if it's already a URL or a relative path
              if (pdfPath.startsWith("http")) {
                setPdfUrl(pdfPath);
              } else {
                // Assume it's a relative path, construct the API URL
                setPdfUrl(`http://localhost:4000/api/pos/${decodedPoNumber}/pdf?file=${encodeURIComponent(pdfPath)}`);
              }
            }
            setLoading(false);
            return;
          }
        } catch (apiError) {
          console.warn("API fetch failed, trying mock data:", apiError);
        }

        // Fallback to mock data
        const mockPO = await getMockPO(decodedPoNumber);
        if (mockPO) {
          setPo(mockPO);
          setItems([...mockPO.AutoGeneratedContent]);
          setUsingMock(true);
          
          // For mock data, set a placeholder PDF URL or handle gracefully
          if (mockPO.PO && mockPO.PO.length > 0) {
            const pdfPath = mockPO.PO.find((p: string) => p.includes("uploads/")) || mockPO.PO[0];
            if (pdfPath.startsWith("http")) {
              setPdfUrl(pdfPath);
            } else {
              // Try to construct API URL even for mock
              setPdfUrl(`http://localhost:4000/api/pos/${decodedPoNumber}/pdf?file=${encodeURIComponent(pdfPath)}`);
            }
          }
        } else {
          console.error("PO not found in mock data either");
        }
      } catch (error) {
        console.error("Error fetching PO:", error);
      } finally {
        setLoading(false);
      }
    };

    fetchPO();
  }, [poNumber]);

  const handleToggleIncomplete = (index: number) => {
    const updatedItems = [...items];
    updatedItems[index] = {
      ...updatedItems[index],
      IsIncomplete: !updatedItems[index].IsIncomplete,
    };
    setItems(updatedItems);
  };

  const handleUpdateItem = (index: number, item: POItem) => {
    const updatedItems = [...items];
    updatedItems[index] = item;
    setItems(updatedItems);
  };

  const createBlankItem = (): POItem => {
    return {
      IsIncomplete: false,
      ClientItemCode: "",
      ChandraItemCode: "",
      JobBagNumber: "",
      Description: "",
      Quantity: 0,
      MetalType: "",
      MetalColor: "",
      Category: "",
      Remarks: "",
      StampingInstructions: "",
      StampRequired: false,
      InvoiceNumber: "",
    };
  };

  const handleAddItem = () => {
    const blankItem = createBlankItem();
    const updatedItems = [...items];
    // Insert the new item just before the current item (at currentIndex)
    updatedItems.splice(currentIndex, 0, blankItem);
    setItems(updatedItems);
    setIsAddingNewItem(true);
    // The currentIndex stays the same, which now points to the new blank item
  };

  const handleSaveNewItem = () => {
    setIsAddingNewItem(false);
    // Item is already in the items array, just exit add mode
  };

  const handleCancelNewItem = () => {
    const updatedItems = [...items];
    // Remove the item at currentIndex (the temporary new item)
    updatedItems.splice(currentIndex, 1);
    setItems(updatedItems);
    setIsAddingNewItem(false);
    // Adjust currentIndex if we removed the last item
    if (currentIndex >= updatedItems.length && updatedItems.length > 0) {
      setCurrentIndex(updatedItems.length - 1);
    } else if (updatedItems.length === 0) {
      setCurrentIndex(0);
    }
  };

  const handlePrevious = () => {
    if (currentIndex > 0) {
      setCurrentIndex(currentIndex - 1);
    }
  };

  const handleNext = () => {
    if (currentIndex < items.length - 1) {
      setCurrentIndex(currentIndex + 1);
    }
  };

  const handleFinishReview = async () => {
    if (!po) return;

    setSaving(true);
    try {
      // Normalize items data - convert dates to strings and ensure Size property
      // This matches the API's expected format
      const normalizedItems = items.map((item) => {
        const normalized = {
          IsIncomplete: item.IsIncomplete,
          ClientItemCode: item.ClientItemCode,
          ChandraItemCode: item.ChandraItemCode,
          JobBagNumber: item.JobBagNumber,
          Description: item.Description,
          Quantity: item.Quantity,
          MetalType: item.MetalType,
          MetalColor: item.MetalColor,
          Category: item.Category,
          Remarks: item.Remarks,
          StampingInstructions: item.StampingInstructions,
          StampRequired: item.StampRequired,
          InvoiceNumber: item.InvoiceNumber,
          Size: item.Size || item.size || undefined,
          DeadlineDate: item.DeadlineDate
            ? typeof item.DeadlineDate === "string"
              ? item.DeadlineDate
              : new Date(item.DeadlineDate).toISOString().split("T")[0]
            : undefined,
          ShippingDate: item.ShippingDate
            ? typeof item.ShippingDate === "string"
              ? item.ShippingDate
              : new Date(item.ShippingDate).toISOString().split("T")[0]
            : null,
        };

        return normalized;
      });

      // Update the PO with reviewed items - ensure data format matches API expectations
      const updatedPO = {
        ...po,
        PODate: typeof po.PODate === "string" ? po.PODate : new Date(po.PODate).toISOString().split("T")[0],
        Items: normalizedItems,
        AutoGeneratedContent: normalizedItems,
        IncompleteItems: normalizedItems.filter((item) => item.IsIncomplete).length,
        Status: items.some((item) => item.IsIncomplete)
          ? "Reviewed & Incomplete"
          : "Reviewed",
        ClientReminderCount: po.ClientReminderCount ?? null,
      };

      // Only try to save if not using mock data
      if (!usingMock) {
        const res = await fetch(`http://localhost:4000/api/pos/${po.PONumber}`, {
          method: "PUT",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify(updatedPO),
        });

        if (!res.ok) {
          // Try to get error message from response
          let errorMessage = "Failed to save review";
          try {
            const errorData = await res.json();
            errorMessage = errorData.error || errorData.message || errorMessage;
          } catch {
            errorMessage = `Failed to save review: ${res.status} ${res.statusText}`;
          }
          throw new Error(errorMessage);
        }
      } else {
        console.log("Mock mode: Review data would be saved:", updatedPO);
      }

      // Navigate back to home page
      router.push("/");
    } catch (error) {
      console.error("Error saving review:", error);
      const errorMessage = error instanceof Error ? error.message : "Failed to save review. Please try again.";
      alert(errorMessage);
    } finally {
      setSaving(false);
    }
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <div className="text-lg">Loading...</div>
      </div>
    );
  }

  if (!po) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <div className="text-lg text-red-600">PO not found</div>
      </div>
    );
  }

  const currentItem = items[currentIndex];
  const hasIncomplete = items.length > 0 && items.some((item) => item.IsIncomplete);
  const incompleteCount = items.filter((item) => item.IsIncomplete).length;

  return (
    <div className="flex flex-col h-screen bg-gray-50">
      {/* Header */}
      <div className="bg-white border-b border-gray-200 px-6 py-4 flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">
            Review PO: {decodeURIComponent(poNumber)}
            {usingMock && (
              <span className="ml-2 text-sm font-normal text-orange-600 bg-orange-50 px-2 py-1 rounded">
                (Mock Data)
              </span>
            )}
          </h1>
          <p className="text-sm text-gray-600 mt-1">
            {po.ClientName} • {items.length} items • {incompleteCount} incomplete
          </p>
        </div>
        <Link
          href="/"
          className="px-4 py-2 rounded-md border border-gray-300 bg-white hover:bg-gray-100 text-gray-700 font-medium transition-colors"
        >
          Back to Dashboard
        </Link>
      </div>

      {/* Main Content */}
      <div className="flex-1 flex overflow-hidden">
        {/* Left Side - PDF Viewer */}
        <div className="w-1/2 border-r border-gray-200 bg-gray-100 flex flex-col">
          <div className="bg-white border-b border-gray-200 px-4 py-3">
            <h2 className="text-lg font-semibold text-gray-900">PO Document</h2>
          </div>
          <div className="flex-1 overflow-auto p-4">
            {pdfUrl ? (
              <iframe
                src={pdfUrl}
                className="w-full h-full border border-gray-300 rounded-lg bg-white"
                title="PO PDF"
              />
            ) : (
              <div className="flex items-center justify-center h-full text-gray-500">
                <div className="text-center">
                  <p className="mb-2">No PDF available</p>
                  <p className="text-sm text-gray-400">PDF viewer will appear here when available</p>
                </div>
              </div>
            )}
          </div>
        </div>

        {/* Right Side - Item Review */}
        <div className="w-1/2 flex flex-col bg-white">
          <div className="bg-gray-50 border-b border-gray-200 px-4 py-3 flex items-center justify-between">
            <h2 className="text-lg font-semibold text-gray-900">Item Review</h2>
            <div className="text-sm text-gray-600">
              Progress: {currentIndex + 1} / {items.length}
            </div>
          </div>

          <div className="flex-1 overflow-auto p-6">
            {currentItem ? (
              <ItemCard
                item={currentItem}
                index={currentIndex}
                totalItems={items.length}
                onToggleIncomplete={handleToggleIncomplete}
                onUpdateItem={handleUpdateItem}
                isNewItem={isAddingNewItem}
                onSaveNewItem={handleSaveNewItem}
                onCancelNewItem={handleCancelNewItem}
              />
            ) : (
              <div className="flex items-center justify-center h-full text-gray-500">
                <div className="text-center">
                  <p className="mb-2">No items to review</p>
                  <p className="text-sm text-gray-400">Items will appear here when available</p>
                </div>
              </div>
            )}
          </div>

          {/* Navigation Footer */}
          <div className="border-t border-gray-200 bg-gray-50 px-6 py-4">
            <div className="flex items-center justify-between">
              <button
                onClick={handlePrevious}
                disabled={currentIndex === 0 || isAddingNewItem}
                className={`px-4 py-2 rounded-md font-medium transition-colors ${
                  currentIndex === 0 || isAddingNewItem
                    ? "bg-gray-200 text-gray-400 cursor-not-allowed"
                    : "bg-white border border-gray-300 text-gray-700 hover:bg-gray-50"
                }`}
              >
                ← Previous
              </button>

              <div className="flex items-center gap-3">
                {!isAddingNewItem && (
                  <button
                    onClick={handleAddItem}
                    className="px-4 py-2 rounded-md bg-green-600 text-white font-medium hover:bg-green-700 transition-colors"
                  >
                    + Add Item
                  </button>
                )}
                {hasIncomplete && !isAddingNewItem && (
                  <span className="text-sm text-red-600 font-medium">
                    ⚠️ {incompleteCount} incomplete item(s)
                  </span>
                )}
                {!isAddingNewItem && (
                  <button
                    onClick={handleFinishReview}
                    disabled={saving}
                    className="px-6 py-2 rounded-md bg-blue-600 text-white font-medium hover:bg-blue-700 disabled:bg-blue-400 disabled:cursor-not-allowed transition-colors"
                  >
                    {saving ? "Saving..." : "Finish Review"}
                  </button>
                )}
              </div>

              <button
                onClick={handleNext}
                disabled={currentIndex === items.length - 1 || isAddingNewItem}
                className={`px-4 py-2 rounded-md font-medium transition-colors ${
                  currentIndex === items.length - 1 || isAddingNewItem
                    ? "bg-gray-200 text-gray-400 cursor-not-allowed"
                    : "bg-white border border-gray-300 text-gray-700 hover:bg-gray-50"
                }`}
              >
                Next →
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}


