"use client";

import { useEffect, useState, use } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { PurchaseOrder, POItem } from "@/types/po";
import ItemCard from "../components/ItemCard";
import EmailDialog from "../components/EmailDialog";
import { getApiEndpoint } from "@/lib/api";

// Mock data for fallback
async function getMockPO(poNumber: string): Promise<PurchaseOrder | null> {
  try {
    const response = await fetch("/test_PO_response.json");
    const data: PurchaseOrder[] = await response.json();
    const po = data.find((p) => p.PONumber === poNumber);
    if (po) {
      // Ensure PO array has at least one entry
      if (!po.PO || po.PO.length === 0) {
        po.PO = ["PO-108248-Uneek.pdf"];
      }
      return po;
    }
    return null;
  } catch (error) {
    console.error("Error loading mock data:", error);
    return null;
  }
}

export default function ReviewPage({ params }: { params: Promise<{ poNumber: string }> }) {
  const { poNumber } = use(params);
  const router = useRouter();
  const [po, setPo] = useState<PurchaseOrder | null>(null);
  const [items, setItems] = useState<POItem[]>([]);
  const [currentIndex, setCurrentIndex] = useState(0);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [pdfUrl, setPdfUrl] = useState<string>("");
  const [usingMock, setUsingMock] = useState(false);
  const [isAddingNewItem, setIsAddingNewItem] = useState(false);
  const [isEmailDialogOpen, setIsEmailDialogOpen] = useState(false);
  const [emailContent, setEmailContent] = useState<string>("");
  const [isDeleting, setIsDeleting] = useState(false);
  const [showDeleteConfirm, setShowDeleteConfirm] = useState(false);

  useEffect(() => {
    const fetchPO = async () => {
      try {
        const decodedPoNumber = decodeURIComponent(poNumber);
        
        // Try to fetch from API first
        try {
          const res = await fetch(getApiEndpoint(`/po/${decodedPoNumber}`));
          if (res.ok) {
            const data: PurchaseOrder = await res.json();
            setPo(data);
            // Initialize items from AutoGeneratedContent
            setItems([...data.AutoGeneratedContent]);
            
            // Set PDF URL - always use backend endpoint to proxy through backend
            if (data.PO && data.PO.length > 0) {
              const s3Url = data.PO.find((p: string) => p.startsWith("http://") || p.startsWith("https://"));
              const pdfPath = s3Url || data.PO.find((p: string) => p.includes("uploads/")) || data.PO[0];
              // Always use backend endpoint to proxy S3 files and local files
              setPdfUrl(getApiEndpoint(`/po/${decodedPoNumber}/pdf?file=${encodeURIComponent(pdfPath)}`));
            }
            setLoading(false);
            return;
          }
        } catch (apiError) {
          console.warn("API fetch failed, trying mock data:", apiError);
        }

        // Fallback to mock data
        const mockPO = await getMockPO(decodedPoNumber);
        if (mockPO) {
          setPo(mockPO);
          setItems([...mockPO.AutoGeneratedContent]);
          setUsingMock(true);
          
          // For mock data, set a placeholder PDF URL or handle gracefully
          if (mockPO.PO && mockPO.PO.length > 0) {
            const s3Url = mockPO.PO.find((p: string) => p.startsWith("http://") || p.startsWith("https://"));
            const pdfPath = s3Url || mockPO.PO.find((p: string) => p.includes("uploads/")) || mockPO.PO[0];
            // Always use backend endpoint to proxy S3 files and local files
            setPdfUrl(getApiEndpoint(`/po/${decodedPoNumber}/pdf?file=${encodeURIComponent(pdfPath)}`));
          }
        } else {
          console.error("PO not found in mock data either");
        }
      } catch (error) {
        console.error("Error fetching PO:", error);
      } finally {
        setLoading(false);
      }
    };

    fetchPO();
  }, [poNumber]);

  const handleToggleIncomplete = (index: number) => {
    const updatedItems = [...items];
    updatedItems[index] = {
      ...updatedItems[index],
      IsIncomplete: !updatedItems[index].IsIncomplete,
    };
    setItems(updatedItems);
  };

  const handleUpdateItem = (index: number, item: POItem) => {
    const updatedItems = [...items];
    updatedItems[index] = item;
    setItems(updatedItems);
  };

  const createBlankItem = (): POItem => {
    return {
      IsIncomplete: true,
      VendorStyleCode: "",
      ItemRefNo: "",
      ItemPoNo: "",
      OrderQty: 0,
      Metal: "",
      Tone: "",
      Category: "",
      StockType: null,
      MakeType: null,
      CustomerProductionInstruction: null,
      SpecialRemarks: null,
      DesignProductionInstruction: null,
      StampInstruction: null,
      ItemSize: null,
      DeadlineDate: null,
      ShippingDate: null,
      InvoiceNumber: "",
    };
  };

  const handleAddItem = () => {
    const blankItem = createBlankItem();
    const updatedItems = [...items];
    // Insert the new item just before the current item (at currentIndex)
    updatedItems.splice(currentIndex, 0, blankItem);
    setItems(updatedItems);
    setIsAddingNewItem(true);
    // The currentIndex stays the same, which now points to the new blank item
  };

  const handleSaveNewItem = () => {
    setIsAddingNewItem(false);
    // Item is already in the items array, just exit add mode
  };

  const handleCancelNewItem = () => {
    const updatedItems = [...items];
    // Remove the item at currentIndex (the temporary new item)
    updatedItems.splice(currentIndex, 1);
    setItems(updatedItems);
    setIsAddingNewItem(false);
    // Adjust currentIndex if we removed the last item
    if (currentIndex >= updatedItems.length && updatedItems.length > 0) {
      setCurrentIndex(updatedItems.length - 1);
    } else if (updatedItems.length === 0) {
      setCurrentIndex(0);
    }
  };

  const handlePrevious = () => {
    if (currentIndex > 0) {
      setCurrentIndex(currentIndex - 1);
    }
  };

  const handleNext = () => {
    if (currentIndex < items.length - 1) {
      setCurrentIndex(currentIndex + 1);
    }
  };

  const handleExportCompletedItems = async () => {
    if (!po || !items.length) return;

    const completedItems = items.filter((item) => !item.IsIncomplete);
    if (completedItems.length === 0) {
      alert("There are no completed items to export yet.");
      return;
    }

    const xlsx = await import("xlsx");

    const exportRows = completedItems.map((item) => {
      const normalizeDate = (value: POItem["DeadlineDate"]) => {
        if (!value) return "";
        const d = typeof value === "string" ? new Date(value) : new Date(value);
        return isNaN(d.getTime()) ? "" : d.toISOString().split("T")[0];
      };

      return {
        VendorStyleCode: item.VendorStyleCode ?? "",
        ItemRefNo: item.ItemRefNo ?? "",
        ItemPoNo: item.ItemPoNo ?? "",
        OrderQty: item.OrderQty ?? 0,
        Metal: item.Metal ?? "",
        Tone: item.Tone ?? "",
        Category: item.Category ?? "",
        StockType: item.StockType ?? "",
        MakeType: item.MakeType ?? "",
        CustomerProductionInstruction: item.CustomerProductionInstruction ?? "",
        SpecialRemarks: item.SpecialRemarks ?? "",
        DesignProductionInstruction: item.DesignProductionInstruction ?? "",
        StampInstruction: item.StampInstruction ?? "",
        ItemSize: item.ItemSize ?? "",
        DeadlineDate: normalizeDate(item.DeadlineDate),
        ShippingDate: normalizeDate(item.ShippingDate),
        InvoiceNumber: item.InvoiceNumber ?? "",
      };
    });

    const worksheet = xlsx.utils.json_to_sheet(exportRows);
    const workbook = xlsx.utils.book_new();
    xlsx.utils.book_append_sheet(workbook, worksheet, "Completed Items");

    const safePONumber = (po.PONumber || decodeURIComponent(poNumber)).replace(/[^\w\-]+/g, "_");
    xlsx.writeFile(workbook, `${safePONumber}_completed_items.xlsx`);
  };

  const generateEmailContent = (): string => {
    if (!po || !items.length) return "";

    const incompleteItems = items.filter((item) => item.IsIncomplete);
    if (incompleteItems.length === 0) {
      return "All items are complete. No email needed.";
    }

    // Field labels mapping - only include important fields
    const fieldChecks: Array<{ key: keyof POItem; label: string }> = [
      { key: "VendorStyleCode", label: "Vendor Style Code" },
      { key: "ItemRefNo", label: "Item Ref No" },
      { key: "Metal", label: "Metal" },
      { key: "Tone", label: "Tone" },
      { key: "Category", label: "Category" },
      { key: "OrderQty", label: "Order Quantity" },
      { key: "StockType", label: "Stock Type" },
      { key: "MakeType", label: "Make Type" },
      { key: "ItemSize", label: "Item Size" },
      { key: "DeadlineDate", label: "Deadline Date" },
      { key: "ShippingDate", label: "Shipping Date" },
      { key: "CustomerProductionInstruction", label: "Customer Production Instruction" },
      { key: "SpecialRemarks", label: "Special Remarks" },
      { key: "DesignProductionInstruction", label: "Design Production Instruction" },
      { key: "StampInstruction", label: "Stamp Instruction" },
    ];

    // Helper function to check if a field is missing/empty
    const isFieldMissing = (item: POItem, field: keyof POItem): boolean => {
      const value = item[field];
      if (value === null || value === undefined) return true;
      if (typeof value === "string" && value.trim() === "") return true;
      return false;
    };

    // Build email content - short and precise
    let email = `Subject: Missing Details for PO ${po.PONumber}\n\n`;
    email += `Dear ${po.ClientName},\n\n`;
    email += `Please provide the following missing information for PO ${po.PONumber}:\n\n`;

    incompleteItems.forEach((item, index) => {
      const missingFields: string[] = [];
      
      fieldChecks.forEach(({ key, label }) => {
        if (isFieldMissing(item, key)) {
          missingFields.push(label);
        }
      });

      if (missingFields.length > 0) {
        // Use item identifier or index
        const identifier = item.VendorStyleCode || item.ItemRefNo || item.ItemPoNo || `Item ${index + 1}`;
        email += `${index + 1}. ${identifier}\n`;
        email += `   Missing: ${missingFields.join(", ")}\n\n`;
      }
    });

    email += `Please respond at your earliest convenience.\n\nThank you.`;

    return email;
  };

  const handleGenerateEmail = () => {
    const content = generateEmailContent();
    setEmailContent(content);
    setIsEmailDialogOpen(true);
  };

  const handleDeletePO = async () => {
    if (!po || usingMock) {
      alert("Cannot delete PO in mock mode");
      return;
    }

    setIsDeleting(true);
    try {
      const res = await fetch(getApiEndpoint(`/po/${po.PONumber}`), {
        method: "DELETE",
      });

      if (!res.ok) {
        const errorData = await res.json().catch(() => ({ message: "Delete failed" }));
        throw new Error(errorData.message || errorData.error || "Failed to delete PO");
      }

      // Navigate back to dashboard after successful deletion
      router.push("/");
    } catch (error) {
      console.error("Error deleting PO:", error);
      const errorMessage = error instanceof Error ? error.message : "Failed to delete PO. Please try again.";
      alert(errorMessage);
    } finally {
      setIsDeleting(false);
      setShowDeleteConfirm(false);
    }
  };

  const handleFinishReview = async () => {
    if (!po) return;

    setSaving(true);
    try {
      // Normalize items data - convert dates to strings
      // This matches the API's expected format
      const normalizedItems = items.map((item) => {
        const normalized = {
          IsIncomplete: item.IsIncomplete,
          VendorStyleCode: item.VendorStyleCode,
          ItemRefNo: item.ItemRefNo,
          ItemPoNo: item.ItemPoNo,
          OrderQty: item.OrderQty,
          Metal: item.Metal,
          Tone: item.Tone,
          Category: item.Category,
          StockType: item.StockType ?? null,
          MakeType: item.MakeType ?? null,
          CustomerProductionInstruction: item.CustomerProductionInstruction ?? null,
          SpecialRemarks: item.SpecialRemarks ?? null,
          DesignProductionInstruction: item.DesignProductionInstruction ?? null,
          StampInstruction: item.StampInstruction ?? null,
          ItemSize: item.ItemSize ?? null,
          DeadlineDate: item.DeadlineDate
            ? typeof item.DeadlineDate === "string"
              ? item.DeadlineDate
              : new Date(item.DeadlineDate).toISOString().split("T")[0]
            : null,
          ShippingDate: item.ShippingDate
            ? typeof item.ShippingDate === "string"
              ? item.ShippingDate
              : new Date(item.ShippingDate).toISOString().split("T")[0]
            : null,
          InvoiceNumber: item.InvoiceNumber,
        };

        return normalized;
      });

      // Update the PO with reviewed items - ensure data format matches API expectations
      const updatedPO = {
        ...po,
        PODate: typeof po.PODate === "string" ? po.PODate : new Date(po.PODate).toISOString().split("T")[0],
        Items: normalizedItems,
        AutoGeneratedContent: normalizedItems,
        IncompleteItems: normalizedItems.filter((item) => item.IsIncomplete).length,
        Status: items.some((item) => item.IsIncomplete)
          ? "Reviewed & Incomplete"
          : "Reviewed",
        ClientReminderCount: po.ClientReminderCount ?? null,
      };

      // Only try to save if not using mock data
      if (!usingMock) {
        const res = await fetch(getApiEndpoint(`/po/${po.PONumber}`), {
          method: "PUT",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify(updatedPO),
        });

        if (!res.ok) {
          // Try to get error message from response
          let errorMessage = "Failed to save review";
          try {
            const errorData = await res.json();
            errorMessage = errorData.error || errorData.message || errorMessage;
          } catch {
            errorMessage = `Failed to save review: ${res.status} ${res.statusText}`;
          }
          throw new Error(errorMessage);
        }
      } else {
        console.log("Mock mode: Review data would be saved:", updatedPO);
      }

      // Navigate back to home page
      router.push("/");
    } catch (error) {
      console.error("Error saving review:", error);
      const errorMessage = error instanceof Error ? error.message : "Failed to save review. Please try again.";
      alert(errorMessage);
    } finally {
      setSaving(false);
    }
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-screen bg-gradient-to-br from-slate-50 to-slate-100">
        <div className="text-center">
          <svg className="animate-spin h-12 w-12 text-blue-600 mx-auto mb-4" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
            <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
            <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
          </svg>
          <div className="text-lg font-medium text-slate-700">Loading purchase order...</div>
        </div>
      </div>
    );
  }

  if (!po) {
    return (
      <div className="flex items-center justify-center min-h-screen bg-gradient-to-br from-slate-50 to-slate-100">
        <div className="text-center">
          <div className="w-16 h-16 rounded-full bg-red-100 flex items-center justify-center mx-auto mb-4">
            <svg className="w-8 h-8 text-red-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
            </svg>
          </div>
          <div className="text-xl font-semibold text-slate-900 mb-2">PO not found</div>
          <div className="text-slate-600 mb-6">The purchase order you&apos;re looking for doesn&apos;t exist.</div>
          <Link
            href="/"
            className="inline-flex items-center px-4 py-2 rounded-lg bg-blue-600 text-white font-medium hover:bg-blue-700 transition-colors"
          >
            Back to Dashboard
          </Link>
        </div>
      </div>
    );
  }

  const currentItem = items[currentIndex];
  const hasIncomplete = items.length > 0 && items.some((item) => item.IsIncomplete);
  const incompleteCount = items.filter((item) => item.IsIncomplete).length;
  const completedCount = items.length - incompleteCount;

  return (
    <div className="flex flex-col h-screen bg-gradient-to-br from-slate-50 to-slate-100">
      {/* Header */}
      <div className="bg-white border-b border-slate-200 shadow-sm px-6 py-4 flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-slate-900 flex items-center gap-2">
            Review PO: <span className="text-blue-600">{decodeURIComponent(poNumber)}</span>
            {usingMock && (
              <span className="ml-2 text-xs font-medium text-orange-600 bg-orange-50 border border-orange-200 px-2 py-1 rounded-full">
                Mock Data
              </span>
            )}
          </h1>
          <p className="text-sm text-slate-600 mt-1 flex items-center gap-2">
            <span className="font-medium">{po.ClientName}</span>
            <span>•</span>
            <span>{items.length} {items.length === 1 ? "item" : "items"}</span>
            {incompleteCount > 0 && (
              <>
                <span>•</span>
                <span className="text-red-600 font-medium">{incompleteCount} incomplete</span>
              </>
            )}
          </p>
        </div>
        <div className="flex items-center gap-3">
          <button
            onClick={handleGenerateEmail}
            disabled={!hasIncomplete || items.length === 0}
            className={`px-4 py-2 rounded-lg border font-medium transition-colors flex items-center gap-2 ${
              !hasIncomplete || items.length === 0
                ? "border-slate-300 bg-slate-100 text-slate-400 cursor-not-allowed"
                : "border-blue-300 bg-blue-50 hover:bg-blue-100 text-blue-700"
            }`}
          >
            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
            </svg>
            Generate Email
          </button>
          {!usingMock && (
            <button
              onClick={() => setShowDeleteConfirm(true)}
              disabled={isDeleting}
              className="px-4 py-2 rounded-lg border border-red-300 bg-red-50 hover:bg-red-100 text-red-700 font-medium transition-colors disabled:bg-slate-100 disabled:text-slate-400 disabled:cursor-not-allowed flex items-center gap-2"
            >
              {isDeleting ? (
                <>
                  <svg className="animate-spin h-4 w-4" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                  </svg>
                  Deleting...
                </>
              ) : (
                <>
                  <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                  </svg>
                  Delete PO
                </>
              )}
            </button>
          )}
          <Link
            href="/"
            className="px-4 py-2 rounded-lg border border-slate-300 bg-white hover:bg-slate-50 text-slate-700 font-medium transition-colors flex items-center gap-2"
          >
            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 19l-7-7m0 0l7-7m-7 7h18" />
            </svg>
            Dashboard
          </Link>
        </div>
      </div>

      {/* Main Content */}
      <div className="flex-1 flex overflow-hidden gap-4 p-4">
        {/* Left Side - PDF Viewer */}
        <div className="w-1/2 bg-white rounded-xl shadow-sm border border-slate-200 flex flex-col min-w-0 overflow-hidden">
          <div className="bg-gradient-to-r from-slate-50 to-white border-b border-slate-200 px-5 py-4 shrink-0">
            <h2 className="text-lg font-semibold text-slate-900 flex items-center gap-2">
              <svg className="w-5 h-5 text-slate-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
              </svg>
              PO Document
            </h2>
            {po?.PO && po.PO.length > 0 && (
              <p className="text-sm text-slate-600 mt-1 font-mono">
                {po.PO[0].split('/').pop() || po.PO[0]}
              </p>
            )}
          </div>
          <div className="flex-1 overflow-hidden p-4 bg-slate-50">
            {pdfUrl ? (
              <iframe
                src={pdfUrl}
                className="w-full h-full border border-slate-300 rounded-lg bg-white shadow-sm min-h-0"
                title="PO PDF"
                style={{ minHeight: 0 }}
              />
            ) : (
              <div className="flex items-center justify-center h-full">
                <div className="text-center">
                  <div className="w-16 h-16 rounded-full bg-slate-200 flex items-center justify-center mx-auto mb-4">
                    <svg className="w-8 h-8 text-slate-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                    </svg>
                  </div>
                  <p className="text-slate-700 font-medium mb-1">No PDF available</p>
                  <p className="text-sm text-slate-500">PDF viewer will appear here when available</p>
                </div>
              </div>
            )}
          </div>
        </div>

        {/* Right Side - Item Review */}
        <div className="w-1/2 flex flex-col bg-white rounded-xl shadow-sm border border-slate-200 overflow-hidden">
          <div className="bg-gradient-to-r from-blue-50 to-indigo-50 border-b border-slate-200 px-5 py-4 flex items-center justify-between">
            <h2 className="text-lg font-semibold text-slate-900 flex items-center gap-2">
              <svg className="w-5 h-5 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2" />
              </svg>
              Item Review
            </h2>
            <div className="flex flex-col items-end">
              <div className="flex items-center gap-2 text-sm font-medium text-slate-700">
                <span>Progress:</span>
                <span className="text-blue-600">{currentIndex + 1} / {items.length}</span>
              </div>
              <span className="text-xs text-slate-500 mt-0.5">
                {completedCount} of {items.length} completed
              </span>
            </div>
          </div>

          <div className="flex-1 overflow-auto p-6">
            {currentItem ? (
              <ItemCard
                item={currentItem}
                index={currentIndex}
                totalItems={items.length}
                onToggleIncomplete={handleToggleIncomplete}
                onUpdateItem={handleUpdateItem}
                isNewItem={isAddingNewItem}
                onSaveNewItem={handleSaveNewItem}
                onCancelNewItem={handleCancelNewItem}
              />
            ) : (
              <div className="flex items-center justify-center h-full text-gray-500">
                <div className="text-center">
                  <p className="mb-2">No items to review</p>
                  <p className="text-sm text-gray-400">Items will appear here when available</p>
                </div>
              </div>
            )}
          </div>

          {/* Navigation Footer */}
          <div className="border-t border-slate-200 bg-gradient-to-r from-slate-50 to-white px-6 py-4">
            <div className="flex items-center justify-between gap-4">
              <button
                onClick={handlePrevious}
                disabled={currentIndex === 0 || isAddingNewItem}
                className={`px-4 py-2 rounded-lg font-medium transition-colors flex items-center gap-2 ${
                  currentIndex === 0 || isAddingNewItem
                    ? "bg-slate-200 text-slate-400 cursor-not-allowed"
                    : "bg-white border border-slate-300 text-slate-700 hover:bg-slate-50 shadow-sm"
                }`}
              >
                <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
                </svg>
                Previous
              </button>

              <div className="flex items-center gap-2 flex-wrap justify-center">
                {!isAddingNewItem && (
                  <button
                    onClick={handleAddItem}
                    className="px-4 py-2 rounded-lg bg-green-600 text-white font-medium hover:bg-green-700 transition-colors shadow-sm flex items-center gap-2"
                  >
                    <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v16m8-8H4" />
                    </svg>
                    Add Item
                  </button>
                )}
                {hasIncomplete && !isAddingNewItem && (
                  <span className="px-3 py-2 rounded-lg bg-red-50 border border-red-200 text-sm text-red-700 font-medium flex items-center gap-1">
                    <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
                    </svg>
                    {incompleteCount} incomplete
                  </span>
                )}
                {!isAddingNewItem && completedCount > 0 && (
                  <button
                    type="button"
                    onClick={handleExportCompletedItems}
                    className="px-4 py-2 rounded-lg border border-blue-300 bg-blue-50 text-blue-700 text-sm font-medium hover:bg-blue-100 transition-colors flex items-center gap-2"
                  >
                    <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                    </svg>
                    Export Excel
                  </button>
                )}
                {!isAddingNewItem && (
                  <button
                    onClick={handleFinishReview}
                    disabled={saving}
                    className="px-6 py-2 rounded-lg bg-gradient-to-r from-blue-600 to-indigo-600 text-white font-medium hover:from-blue-700 hover:to-indigo-700 disabled:from-slate-400 disabled:to-slate-500 disabled:cursor-not-allowed transition-colors shadow-md flex items-center gap-2"
                  >
                    {saving ? (
                      <>
                        <svg className="animate-spin h-4 w-4" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                          <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                          <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                        </svg>
                        Saving...
                      </>
                    ) : (
                      <>
                        <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                        </svg>
                        Finish Review
                      </>
                    )}
                  </button>
                )}
              </div>

              <button
                onClick={handleNext}
                disabled={currentIndex === items.length - 1 || isAddingNewItem}
                className={`px-4 py-2 rounded-lg font-medium transition-colors flex items-center gap-2 ${
                  currentIndex === items.length - 1 || isAddingNewItem
                    ? "bg-slate-200 text-slate-400 cursor-not-allowed"
                    : "bg-white border border-slate-300 text-slate-700 hover:bg-slate-50 shadow-sm"
                }`}
              >
                Next
                <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
                </svg>
              </button>
            </div>
          </div>
        </div>
      </div>
      
      <EmailDialog
        isOpen={isEmailDialogOpen}
        onClose={() => setIsEmailDialogOpen(false)}
        emailContent={emailContent}
      />

      {/* Delete Confirmation Dialog */}
      {showDeleteConfirm && (
        <div className="fixed inset-0 bg-black bg-opacity-60 backdrop-blur-sm flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-xl shadow-2xl p-6 max-w-md w-full mx-4 border border-slate-200">
            <div className="flex items-start gap-4 mb-4">
              <div className="shrink-0 w-10 h-10 rounded-full bg-red-100 flex items-center justify-center">
                <svg className="w-6 h-6 text-red-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
                </svg>
              </div>
              <div className="flex-1">
                <h2 className="text-xl font-bold text-slate-900 mb-2">Delete Purchase Order</h2>
                <p className="text-slate-700 mb-4">
                  Are you sure you want to delete PO <strong className="text-slate-900">{po?.PONumber}</strong>? This action cannot be undone and will delete:
                </p>
                <ul className="list-disc list-inside mt-2 text-sm text-slate-600 space-y-1">
                  <li>The PO from the database</li>
                  <li>All associated items</li>
                  <li>All files from S3</li>
                  <li>All file metadata</li>
                </ul>
              </div>
            </div>
            <div className="flex justify-end gap-3 pt-4 border-t border-slate-200">
              <button
                onClick={() => setShowDeleteConfirm(false)}
                disabled={isDeleting}
                className="px-4 py-2 rounded-lg border border-slate-300 bg-white hover:bg-slate-50 text-slate-700 font-medium transition-colors disabled:opacity-50"
              >
                Cancel
              </button>
              <button
                onClick={handleDeletePO}
                disabled={isDeleting}
                className="px-4 py-2 rounded-lg bg-red-600 text-white font-medium hover:bg-red-700 transition-colors disabled:bg-red-400 disabled:cursor-not-allowed shadow-sm"
              >
                {isDeleting ? "Deleting..." : "Delete"}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}


