import mongoose from "mongoose";
import { fileSchema } from "./file";
import { POItemInterface, poItemSchema } from "./poItem";

interface PO {
    poNumber: string;
    poDate: Date;
    clientName: string;
    totalItems: number;
    incompleteItems: number;
    totalValue: number;
    status: string;
    autoGeneratedContent: POItemInterface[];
    items: POItemInterface[];
    poFiles: File[];
    invoices: string[];
    clientReminderCount: number | null;
}

const poSchema = new mongoose.Schema<PO>({
    poNumber: { type: String, required: true },
    poDate: { type: Date, required: true },
    clientName: { type: String, required: true },
    totalItems: { type: Number, required: true },
    incompleteItems: { type: Number, required: true },
    totalValue: { type: Number, required: true },
    status: { type: String, required: true },
    autoGeneratedContent: { type: [poItemSchema], required: true },
    items: { type: [poItemSchema], required: true },
    poFiles: { type: [fileSchema], required: true },
    invoices: { type: [String], required: true },
    clientReminderCount: { type: Number, default: 0 },
})

const PO = mongoose.model<PO>("PO", poSchema);

export default PO;