import mongoose from "mongoose";
import { fileSchema } from "./file";

interface PO {
    poNumber: string;
    poDate: Date;
    clientName: string;
    totalItems: number;
    incompleteItems: number;
    totalValue: number;
    status: string;
    autoGeneratedContent: mongoose.Types.ObjectId[];
    items: mongoose.Types.ObjectId[];
    poFiles: File[];
    invoices: string[];
    clientReminderCount: number | null;
}

const poSchema = new mongoose.Schema<PO>({
    poNumber: { type: String, required: true },
    poDate: { type: Date, required: true },
    clientName: { type: String, required: true },
    totalItems: { type: Number, required: true },
    incompleteItems: { type: Number, required: true },
    totalValue: { type: Number, required: true },
    status: { type: String, required: true },
    autoGeneratedContent: [{ type: mongoose.Schema.Types.ObjectId, ref: "POItem" }],
    items: [{ type: mongoose.Schema.Types.ObjectId, ref: "POItem" }],
    poFiles: { type: [fileSchema], required: true },
    invoices: { type: [String], required: true },
    clientReminderCount: { type: Number, default: 0 },
}, {
    timestamps: true,
})

const PO = mongoose.model<PO>("PO", poSchema);

export default PO;