export type POStatus = 'New' | 'In Review' | 'Reviewed' | 'Reviewed & Incomplete' | 'Completed' | 'Cancelled';

export interface POItem {
  IsIncomplete: boolean;
  VendorStyleCode: string;
  ItemRefNo: string;
  ItemPoNo: string;
  OrderQty: number;
  Metal: string;
  Tone: string;
  Category: string;
  StockType?: string | null;
  MakeType?: string | null;
  CustomerProductionInstruction?: string | null;
  SpecialRemarks?: string | null;
  DesignProductionInstruction?: string | null;
  StampInstruction?: string | null;
  ItemSize?: string | null;
  DeadlineDate?: Date | string | null;
  ShippingDate?: Date | string | null;
  InvoiceNumber: string;
  ExportedToExcel?: boolean;
  CompletedBy?: string | null; // User ID who marked as complete
  CompletedByName?: string | null; // User name/username who marked as complete
}

export interface PurchaseOrder {
  PONumber: string;
  PODate: Date | string;
  ClientName: string;
  TotalItems: number;
  IncompleteItems: number;
  TotalValue: number;
  Status: POStatus;
  AutoGeneratedContent: POItem[];
  Items: POItem[];
  PO: (string)[]; // URLs for now
  Invoices: (string)[];
  ClientReminderCount: number;
}



