export type POStatus = 'New' | 'In Review' | 'Reviewed' | 'Reviewed & Incomplete' | 'Completed' | 'Cancelled';

export interface POItem {
  IsIncomplete: boolean;
  ClientItemCode: string;
  ChandraItemCode: string;
  JobBagNumber: string;
  Description: string;
  Quantity: number;
  MetalType: string;
  MetalColor: string;
  Category: string;
  Remarks: string;
  Size?: string;
  size?: string; // Allow both for compatibility
  StampingInstructions: string;
  StampRequired: boolean;
  DeadlineDate?: Date | string;
  ShippingDate?: Date | string;
  InvoiceNumber: string;
}

export interface PurchaseOrder {
  PONumber: string;
  PODate: Date | string;
  ClientName: string;
  TotalItems: number;
  IncompleteItems: number;
  TotalValue: number;
  Status: POStatus;
  AutoGeneratedContent: POItem[];
  Items: POItem[];
  PO: (string)[]; // URLs for now
  Invoices: (string)[];
  ClientReminderCount: number;
}



