import fs from 'fs-extra';
import path from 'path';

export interface POItem {
  IsIncomplete: boolean;
  VendorStyleCode: string;
  ItemRefNo: string;
  ItemPoNo: string;
  OrderQty: number;
  Metal: string;
  Tone: string;
  Category: string;
  StockType?: string | null;
  MakeType?: string | null;
  CustomerProductionInstruction?: string | null;
  SpecialRemarks?: string | null;
  DesignProductionInstruction?: string | null;
  StampInstruction?: string | null;
  ItemSize?: string | null;
  DeadlineDate?: string | null;
  ShippingDate?: string | null;
  InvoiceNumber: string;
}

export interface PurchaseOrder {
  PONumber: string;
  PODate: string;
  ClientName: string;
  TotalItems: number;
  IncompleteItems: number;
  TotalValue: number;
  Status: string;
  AutoGeneratedContent: POItem[];
  Items: POItem[];
  PO: string[]; // file paths or URLs
  Invoices: string[];
  ClientReminderCount: number | null;
}

interface DatabaseShape {
  pos: PurchaseOrder[];
}

const dataDir = path.resolve(__dirname, '..', 'data');
const dbPath = path.join(dataDir, 'db.json');

export async function initDb(): Promise<void> {
  await fs.ensureDir(dataDir);
  const exists = await fs.pathExists(dbPath);
  if (!exists) {
    const initial: DatabaseShape = { pos: [] };
    await fs.writeJson(dbPath, initial, { spaces: 2 });
  }
}

async function readDb(): Promise<DatabaseShape> {
  await initDb();
  return fs.readJson(dbPath);
}

async function writeDb(data: DatabaseShape): Promise<void> {
  await fs.writeJson(dbPath, data, { spaces: 2 });
}

export async function listPOs(): Promise<PurchaseOrder[]> {
  const db = await readDb();
  return db.pos;
}

export async function getPO(poNumber: string): Promise<PurchaseOrder | undefined> {
  const db = await readDb();
  return db.pos.find(p => p.PONumber === poNumber);
}

export async function upsertPO(po: PurchaseOrder): Promise<PurchaseOrder> {
  const db = await readDb();
  const idx = db.pos.findIndex(p => p.PONumber === po.PONumber);
  if (idx >= 0) {
    db.pos[idx] = po;
  } else {
    db.pos.push(po);
  }
  await writeDb(db);
  return po;
}


