// FastAPI Response Types
export interface ExtractedLine {
  VendorStyleCode: string;
  Category: string;
  ItemSize?: string | null;
  OrderQty: number;
  Metal: string;
  Tone: string;
  ItemPoNo: string;
  ItemRefNo: string;
  StockType?: string | null;
  MakeType?: string | null;
  CustomerProductionInstruction?: string | null;
  SpecialRemarks?: string | null;
  DesignProductionInstruction?: string | null;
  StampInstruction?: string | null;
}

export interface ExtractedPOResponse {
  total_value: number;
  client_name: string;
  invoice_number: string;
  total_entries: number;
  invoice_date: string;
  items: ExtractedLine[];
}

// Database/API Types
export interface PurchaseOrderItem {
  IsIncomplete: boolean;
  VendorStyleCode: string;
  ItemRefNo: string;
  ItemPoNo: string;
  OrderQty: number;
  Metal: string;
  Tone: string;
  Category: string;
  StockType?: string | null;
  MakeType?: string | null;
  CustomerProductionInstruction?: string | null;
  SpecialRemarks?: string | null;
  DesignProductionInstruction?: string | null;
  StampInstruction?: string | null;
  ItemSize?: string | null;
  DeadlineDate?: string | null;
  ShippingDate?: string | null;
  InvoiceNumber: string;
  ExportedToExcel?: boolean;
}

export interface PurchaseOrder {
  invoice_number: string;
  invoice_date: string;
  client_name: string;
  total_value: number;
  total_entries: number;
  incomplete_items: number;
  status: string;
  auto_generated_content: PurchaseOrderItem[];
  items: PurchaseOrderItem[];
  po_files: FileMetadata[];
  invoices: string[];
  client_reminder_count: number | null;
}

export interface FileMetadata {
  key: string;
  path: string;
  filename: string;
  createdAt?: Date;
  updatedAt?: Date;
}

// Internal types for database operations
export interface POItemRecord {
  isIncomplete: boolean;
  vendorStyleCode: string;
  itemRefNo: string;
  itemPoNo: string;
  orderQty: number;
  metal: string;
  tone: string;
  category: string;
  stockType?: string | null;
  makeType?: string | null;
  customerProductionInstruction?: string | null;
  specialRemarks?: string | null;
  designProductionInstruction?: string | null;
  stampInstruction?: string | null;
  itemSize?: string | null;
  deadlineDate?: Date | null;
  shippingDate?: Date | null;
  invoiceNumber: string;
  exportedToExcel: boolean;
  completedBy?: string | null; // User ID who marked as complete
}

export interface PODocumentShape {
  poNumber: string;
  poDate: Date;
  clientName: string;
  totalItems: number;
  incompleteItems: number;
  totalValue: number;
  status: string;
  autoGeneratedContent: POItemRecord[] | any[];
  items: POItemRecord[] | any[];
  poFiles: FileMetadata[];
  invoices: string[];
  clientReminderCount: number | null;
}

// DTO types for API responses
export interface PurchaseOrderItemDTO {
  IsIncomplete: boolean;
  VendorStyleCode: string;
  ItemRefNo: string;
  ItemPoNo: string;
  OrderQty: number;
  Metal: string;
  Tone: string;
  Category: string;
  StockType?: string | null;
  MakeType?: string | null;
  CustomerProductionInstruction?: string | null;
  SpecialRemarks?: string | null;
  DesignProductionInstruction?: string | null;
  StampInstruction?: string | null;
  ItemSize?: string | null;
  DeadlineDate?: string | null;
  ShippingDate?: string | null;
  InvoiceNumber: string;
  ExportedToExcel?: boolean;
  CompletedBy?: string | null; // User ID who marked as complete
  CompletedByName?: string | null; // User name/username who marked as complete
}

export interface PurchaseOrderDTO {
  PONumber: string;
  PODate: string;
  ClientName: string;
  TotalItems: number;
  IncompleteItems: number;
  TotalValue: number;
  Status: string;
  AutoGeneratedContent: PurchaseOrderItemDTO[];
  Items: PurchaseOrderItemDTO[];
  PO: string[];
  Invoices: string[];
  ClientReminderCount: number;
}

