export interface PurchaseOrderItemDTO {
  IsIncomplete: boolean;
  ClientItemCode: string;
  ChandraItemCode: string;
  JobBagNumber: string;
  Description: string;
  Quantity: number;
  MetalType: string;
  MetalColor: string;
  Category: string;
  Remarks: string;
  Size?: string;
  size?: string;
  StampingInstructions: string;
  StampRequired: boolean;
  DeadlineDate?: string | null;
  ShippingDate?: string | null;
  InvoiceNumber: string;
}

export interface PurchaseOrderDTO {
  PONumber: string;
  PODate: string;
  ClientName: string;
  TotalItems: number;
  IncompleteItems: number;
  TotalValue: number;
  Status: string;
  AutoGeneratedContent: PurchaseOrderItemDTO[];
  Items: PurchaseOrderItemDTO[];
  PO: string[];
  Invoices: string[];
  ClientReminderCount: number | null;
}

export interface ExtractedLine {
  StyleCode?: string;
  Category?: string;
  ItemSize?: string | number;
  OrderQty?: string | number;
  Metal?: string;
  Tone?: string;
  ItemPoNo?: string;
  ItemRefNo?: string;
  StockType?: string;
  MakeType?: string;
  CustomerProductionInstruction?: string;
  SpecialRemarks?: string;
  DesignProductionInstruction?: string;
  StampInstruction?: string;
}

export interface ExtractedPOResponse {
  lines: ExtractedLine[];
  total_value: number;
  client_name: string;
  invoice_number: string;
  total_entries: number;
  invoice_date: string;
}

export interface FileMetadata {
  key: string;
  path: string;
  filename: string;
  createdAt?: Date;
  updatedAt?: Date;
}

export interface POItemRecord {
  isIncomplete: boolean;
  clientItemCode: string;
  chandraItemCode: string;
  jobBagNumber: string;
  description: string;
  quantity: number;
  metalType: string;
  metalColor: string;
  category: string;
  remarks: string;
  size?: string;
  stampingInstructions: string;
  stampRequired: boolean;
  deadlineDate?: Date | null;
  shippingDate?: Date | null;
  invoiceNumber: string;
}

export interface PODocumentShape {
  poNumber: string;
  poDate: Date;
  clientName: string;
  totalItems: number;
  incompleteItems: number;
  totalValue: number;
  status: string;
  autoGeneratedContent: POItemRecord[];
  items: POItemRecord[];
  poFiles: FileMetadata[];
  invoices: string[];
  clientReminderCount: number;
}

